# Generated by Django 5.2 on 2025-04-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='height',
        ),
        migrations.AddField(
            model_name='profile',
            name='height_feet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_inches',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
