# Generated by Django 5.2 on 2025-04-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_profile_height_profile_height_feet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meallog',
            name='meal_name',
            field=models.CharField(default='Default Meal', help_text='Name of the meal (e.g., Grilled Chicken Salad)', max_length=100),
        ),
        migrations.AddField(
            model_name='meallog',
            name='quantity',
            field=models.CharField(default='1 serving', help_text='e.g., 1 bowl, 200g', max_length=100),
        ),
        migrations.AddField(
            model_name='workout',
            name='reps',
            field=models.PositiveIntegerField(blank=True, help_text='Reps per set (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='sets',
            field=models.PositiveIntegerField(blank=True, help_text='Number of sets (if applicable)', null=True),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack')], help_text='Type of meal', max_length=50),
        ),
    ]
