# Generated by Django 5.2 on 2025-04-25 23:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_badge_challenge_userbadge_userchallenge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbadge',
            name='date_awarded',
        ),
        migrations.AddField(
            model_name='userbadge',
            name='awarded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='badge',
            name='emoji',
            field=models.CharField(max_length=5),
        ),
        migrations.DeleteModel(
            name='UserChallenge',
        ),
    ]
